server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rtcdb?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        globally_quoted_identifiers: true
    show-sql: true

  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  flyway:
    baseline-on-migrate: true
    clean-disabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      write_null_map_values: false
    deserialization:
      accept_single_value_as_array: true
    default-property-inclusion: use_defaults

## JWT 鉴权配置
jwt:
  secret: "ay9pL#$RongRTC"
  ttlInMilliSec: -1

## 融云 IM 配置
im:
  appKey: XXXXXXX
  secret: XXXXXXX
  host: http://api-bj.ronghub.com

## 融云 SMS 配置
sms:
  appKey: XXXXXXXXX
  secret: XXXXXXXXX
  host: http://api.sms.ronghub.com
  templateId: XXXXXXXX #登录短信模块 Id

## Redis 连接配置
redis:
  database: 0
  host: 127.0.0.1
  port: 6739
  pass:
  maxIdle: 100
  maxTotal: 300
  testOnBorrow: true

## RongRTC 应用配置
rongrtc:
  domain: http://127.0.0.1 # RongRTC Server 地址，协议://域名:端口
  login:
    sms_verify: false #登录是否校验短信验证码
  filepath: D:/java/RC RTC-Server/files/

  mic:
    transfer_host_expire: 300 #主持人转让信息过期时间，单位秒
    takeover_host_expire: 300 #接管主持人信息过期时间，单位秒

  room:
    expire: 3  # 房间过期多长时间

## 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    cn.rongcloud: INFO
  file:
    max-history: 8
    name: logs/rongrtc.log
    max-size: 100MB
  pattern:
    rolling-file-name: logs/rongrtc.%d{yyyy-MM-dd}.%i.gz